# Generated by Django 4.0.3 on 2022-11-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_object_uuid_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
