# Generated by Django 4.0.3 on 2022-11-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='user',
            new_name='invited_by',
        ),
    ]
